name: CI/CD for React Vite project with Vercel

on:
  push:
    branches:
      - main
      - client-setup


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: go to client directory
        run: cd client

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy project to Vercel
        uses: vercel/vercel-action@v2
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
